### ISSUE TITLE
Toggle component multi event listening support

### ISSUE THREAD

**Issue by jonasjabari** [matestack/matestack-ui-vuejs#6]
I want to be able to listen to multiple events when using the `toggle` component like:

```ruby
toggle show_on: "foo, bar, baz" do
  plain "hey!"
end
```

**Comment by aaron-contreras** [comment]
@jonasjabari This is already part of the `toggle` component's feature-set. However, I'm using this issue to track some refactoring opportunities that the internals might benefit from for code-clarity and better spec documentation.
